package DLMS;


/**
* DLMS/dlmsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DLMS.idl
* Friday, December 11, 2015 7:31:21 PM EST
*/

public abstract class dlmsPOA extends org.omg.PortableServer.Servant
 implements DLMS.dlmsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("openAccount", new java.lang.Integer (0));
    _methods.put ("getLoan", new java.lang.Integer (1));
    _methods.put ("delayPayment", new java.lang.Integer (2));
    _methods.put ("printCustomerInfo", new java.lang.Integer (3));
    _methods.put ("transferLoan", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DLMS/dlms/openAccount
       {
         String Bank = in.read_string ();
         String fName = in.read_string ();
         String lName = in.read_string ();
         String email = in.read_string ();
         String phoneNumber = in.read_string ();
         String password = in.read_string ();
         String $result = null;
         $result = this.openAccount (Bank, fName, lName, email, phoneNumber, password);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // DLMS/dlms/getLoan
       {
         String Bank = in.read_string ();
         String accountNumber = in.read_string ();
         String password = in.read_string ();
         String loanAmount = in.read_string ();
         String $result = null;
         $result = this.getLoan (Bank, accountNumber, password, loanAmount);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // DLMS/dlms/delayPayment
       {
         String Bank = in.read_string ();
         String loanID = in.read_string ();
         String currentD = in.read_string ();
         String newD = in.read_string ();
         String $result = null;
         $result = this.delayPayment (Bank, loanID, currentD, newD);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // DLMS/dlms/printCustomerInfo
       {
         String Bank = in.read_string ();
         String $result = null;
         $result = this.printCustomerInfo (Bank);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // DLMS/dlms/transferLoan
       {
         String loanID = in.read_string ();
         String currentBank = in.read_string ();
         String otherBank = in.read_string ();
         String $result = null;
         $result = this.transferLoan (loanID, currentBank, otherBank);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DLMS/dlms:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public dlms _this() 
  {
    return dlmsHelper.narrow(
    super._this_object());
  }

  public dlms _this(org.omg.CORBA.ORB orb) 
  {
    return dlmsHelper.narrow(
    super._this_object(orb));
  }


} // class dlmsPOA
