package DLMS;


/**
* DLMS/dlms.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DLMS.idl
* Saturday, December 12, 2015 7:13:17 PM EST
*/

public interface dlms extends dlmsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface dlms
