module DLMS {
	interface dlms
	{
		string openAccount(in string Bank, in string fName, in string lName, in string email, in string phoneNumber, in string password);
		string getLoan(in string Bank, in string accountNumber, in string password, in string loanAmount);
		string delayPayment(in string Bank, in string loanID, in string currentD, in string newD);
		string printCustomerInfo(in string Bank);
		string transferLoan(in string loanID, in string currentBank, in string otherBank);
	};
};
