package dfrs;


/**
* dfrs/ServerInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/GIT/DFRS/src/dfrs.idl
* 2016年11月28日 星期一 上午07时35分32秒 EST
*/

public abstract class ServerInterfacePOA extends org.omg.PortableServer.Servant
 implements dfrs.ServerInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("bookFlight", new java.lang.Integer (0));
    _methods.put ("getBookedFlightCount", new java.lang.Integer (1));
    _methods.put ("editFlightRecord", new java.lang.Integer (2));
    _methods.put ("transferReservation", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // dfrs/ServerInterface/bookFlight
       {
         String departure = in.read_string ();
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String address = in.read_string ();
         String phoneNumber = in.read_string ();
         String destination = in.read_string ();
         String flightDate = in.read_string ();
         String flightClass = in.read_string ();
         String $result = null;
         $result = this.bookFlight (departure, firstName, lastName, address, phoneNumber, destination, flightDate, flightClass);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // dfrs/ServerInterface/getBookedFlightCount
       {
         String managerID = in.read_string ();
         String recordType = in.read_string ();
         String $result = null;
         $result = this.getBookedFlightCount (managerID, recordType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // dfrs/ServerInterface/editFlightRecord
       {
         String managerID = in.read_string ();
         String recordID = in.read_string ();
         String fieldName = in.read_string ();
         String newValue = in.read_string ();
         String $result = null;
         $result = this.editFlightRecord (managerID, recordID, fieldName, newValue);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // dfrs/ServerInterface/transferReservation
       {
         String managerID = in.read_string ();
         String passengerID = in.read_string ();
         String currentCity = in.read_string ();
         String otherCity = in.read_string ();
         String $result = null;
         $result = this.transferReservation (managerID, passengerID, currentCity, otherCity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:dfrs/ServerInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServerInterface _this() 
  {
    return ServerInterfaceHelper.narrow(
    super._this_object());
  }

  public ServerInterface _this(org.omg.CORBA.ORB orb) 
  {
    return ServerInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class ServerInterfacePOA
