package dfrs;


/**
* dfrs/ServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/GIT/DFRS/src/dfrs.idl
* 2016年11月27日 星期日 下午04时27分03秒 EST
*/

public interface ServerInterfaceOperations 
{
  String bookFlight (String departure, String firstName, String lastName, String address, String phoneNumber, String destination, String flightClass, String flightDate);
  String getBookedFlightCount (String managerID, String recordType);
  String editFlightRecord (String managerID, String recordID, String fieldName, String newValue);
  String transferReservation (String managerID, String passengerID, String currentCity, String otherCity);
} // interface ServerInterfaceOperations
