package dfrs;


/**
* dfrs/ServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/GIT/DFRS/src/dfrs.idl
* 2016年11月28日 星期一 上午07时35分32秒 EST
*/

public interface ServerInterface extends ServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerInterface
