package dfrs;


/**
* dfrs/ServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/GIT/DFRS/src/dfrs.idl
* 2016年11月27日 星期日 下午04时27分03秒 EST
*/

public interface ServerInterface extends ServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerInterface
